// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/engine.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<FfiEngineEvent> dco_decode_StreamSink_ffi_engine_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiEngineConfig dco_decode_box_autoadd_ffi_engine_config(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfiAudioDevice dco_decode_ffi_audio_device(dynamic raw);

  @protected
  FfiEngineConfig dco_decode_ffi_engine_config(dynamic raw);

  @protected
  FfiEngineEvent dco_decode_ffi_engine_event(dynamic raw);

  @protected
  FfiModelStatus dco_decode_ffi_model_status(dynamic raw);

  @protected
  FfiVoiceInfo dco_decode_ffi_voice_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<FfiAudioDevice> dco_decode_list_ffi_audio_device(dynamic raw);

  @protected
  List<FfiVoiceInfo> dco_decode_list_ffi_voice_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FfiEngineEvent> sse_decode_StreamSink_ffi_engine_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiEngineConfig sse_decode_box_autoadd_ffi_engine_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfiAudioDevice sse_decode_ffi_audio_device(SseDeserializer deserializer);

  @protected
  FfiEngineConfig sse_decode_ffi_engine_config(SseDeserializer deserializer);

  @protected
  FfiEngineEvent sse_decode_ffi_engine_event(SseDeserializer deserializer);

  @protected
  FfiModelStatus sse_decode_ffi_model_status(SseDeserializer deserializer);

  @protected
  FfiVoiceInfo sse_decode_ffi_voice_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<FfiAudioDevice> sse_decode_list_ffi_audio_device(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiVoiceInfo> sse_decode_list_ffi_voice_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffi_engine_event_Sse(
    RustStreamSink<FfiEngineEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_engine_config(
    FfiEngineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_audio_device(
    FfiAudioDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_engine_config(
    FfiEngineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_engine_event(
    FfiEngineEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_model_status(
    FfiModelStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_voice_info(FfiVoiceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_audio_device(
    List<FfiAudioDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_voice_info(
    List<FfiVoiceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
