// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_engine`

/// Start the translation engine. Events stream to `sink`.
Stream<FfiEngineEvent> startEngine({required FfiEngineConfig config}) =>
    RustLib.instance.api.crateApiEngineStartEngine(config: config);

/// Stop the translation engine.
void stopEngine() => RustLib.instance.api.crateApiEngineStopEngine();

/// Check if engine is currently running.
bool isEngineRunning() => RustLib.instance.api.crateApiEngineIsEngineRunning();

/// List audio input devices.
List<FfiAudioDevice> listInputDevices() =>
    RustLib.instance.api.crateApiEngineListInputDevices();

/// List audio output devices.
List<FfiAudioDevice> listOutputDevices() =>
    RustLib.instance.api.crateApiEngineListOutputDevices();

/// Check model readiness.
FfiModelStatus checkModels({
  required String sttModelDir,
  required String vadModelPath,
  required String voicePath,
}) => RustLib.instance.api.crateApiEngineCheckModels(
  sttModelDir: sttModelDir,
  vadModelPath: vadModelPath,
  voicePath: voicePath,
);

/// Audio device info.
class FfiAudioDevice {
  final String name;
  final bool isDefault;
  final bool isInput;

  const FfiAudioDevice({
    required this.name,
    required this.isDefault,
    required this.isInput,
  });

  @override
  int get hashCode => name.hashCode ^ isDefault.hashCode ^ isInput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAudioDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDefault == other.isDefault &&
          isInput == other.isInput;
}

class FfiEngineConfig {
  final String sttBackend;
  final String sttLanguage;
  final String translateFrom;
  final String translateTo;
  final String voicePath;
  final double ttsSpeed;
  final String groqApiKey;
  final String deepgramApiKey;
  final String hfToken;
  final String parakeetModelDir;
  final String vadModelPath;
  final String audioOutput;

  const FfiEngineConfig({
    required this.sttBackend,
    required this.sttLanguage,
    required this.translateFrom,
    required this.translateTo,
    required this.voicePath,
    required this.ttsSpeed,
    required this.groqApiKey,
    required this.deepgramApiKey,
    required this.hfToken,
    required this.parakeetModelDir,
    required this.vadModelPath,
    required this.audioOutput,
  });

  @override
  int get hashCode =>
      sttBackend.hashCode ^
      sttLanguage.hashCode ^
      translateFrom.hashCode ^
      translateTo.hashCode ^
      voicePath.hashCode ^
      ttsSpeed.hashCode ^
      groqApiKey.hashCode ^
      deepgramApiKey.hashCode ^
      hfToken.hashCode ^
      parakeetModelDir.hashCode ^
      vadModelPath.hashCode ^
      audioOutput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiEngineConfig &&
          runtimeType == other.runtimeType &&
          sttBackend == other.sttBackend &&
          sttLanguage == other.sttLanguage &&
          translateFrom == other.translateFrom &&
          translateTo == other.translateTo &&
          voicePath == other.voicePath &&
          ttsSpeed == other.ttsSpeed &&
          groqApiKey == other.groqApiKey &&
          deepgramApiKey == other.deepgramApiKey &&
          hfToken == other.hfToken &&
          parakeetModelDir == other.parakeetModelDir &&
          vadModelPath == other.vadModelPath &&
          audioOutput == other.audioOutput;
}

@freezed
sealed class FfiEngineEvent with _$FfiEngineEvent {
  const FfiEngineEvent._();

  const factory FfiEngineEvent.statusChanged({required String status}) =
      FfiEngineEvent_StatusChanged;
  const factory FfiEngineEvent.transcript({
    required String original,
    required String translated,
  }) = FfiEngineEvent_Transcript;
  const factory FfiEngineEvent.error({required String message}) =
      FfiEngineEvent_Error;
}

/// Model readiness status.
class FfiModelStatus {
  final bool sttReady;
  final String sttPath;
  final bool vadReady;
  final String vadPath;
  final bool voiceReady;
  final String voicePath;

  const FfiModelStatus({
    required this.sttReady,
    required this.sttPath,
    required this.vadReady,
    required this.vadPath,
    required this.voiceReady,
    required this.voicePath,
  });

  @override
  int get hashCode =>
      sttReady.hashCode ^
      sttPath.hashCode ^
      vadReady.hashCode ^
      vadPath.hashCode ^
      voiceReady.hashCode ^
      voicePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiModelStatus &&
          runtimeType == other.runtimeType &&
          sttReady == other.sttReady &&
          sttPath == other.sttPath &&
          vadReady == other.vadReady &&
          vadPath == other.vadPath &&
          voiceReady == other.voiceReady &&
          voicePath == other.voicePath;
}
