// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'engine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `env_fb`, `opt`, `resolve_path`, `running_flag`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Start the translation engine. Events stream to `sink`.
/// Pipeline runs in a dedicated thread with its own tokio runtime.
/// Blocks until pipeline exits (via stop or error).
Stream<FfiEngineEvent> startEngine({required FfiEngineConfig config}) =>
    RustLib.instance.api.crateApiEngineStartEngine(config: config);

/// Stop the translation engine.
void stopEngine() => RustLib.instance.api.crateApiEngineStopEngine();

/// Check if engine is currently running.
bool isEngineRunning() => RustLib.instance.api.crateApiEngineIsEngineRunning();

/// List audio input devices.
List<FfiAudioDevice> listInputDevices() =>
    RustLib.instance.api.crateApiEngineListInputDevices();

/// List audio output devices.
List<FfiAudioDevice> listOutputDevices() =>
    RustLib.instance.api.crateApiEngineListOutputDevices();

/// Check model readiness.
FfiModelStatus checkModels({
  required String sttModelDir,
  required String vadModelPath,
  required String voicePath,
}) => RustLib.instance.api.crateApiEngineCheckModels(
  sttModelDir: sttModelDir,
  vadModelPath: vadModelPath,
  voicePath: voicePath,
);

/// List available voices in the voices/ directory.
List<FfiVoiceInfo> listVoices() =>
    RustLib.instance.api.crateApiEngineListVoices();

/// Record voice from mic for given duration. Blocking — runs in isolate.
Future<String> recordVoice({
  required String name,
  required double durationSecs,
}) => RustLib.instance.api.crateApiEngineRecordVoice(
  name: name,
  durationSecs: durationSecs,
);

/// Precompute voice (.wav → .safetensors). Blocking — runs in isolate.
Future<String> precomputeVoice({required String wavPath}) =>
    RustLib.instance.api.crateApiEnginePrecomputeVoice(wavPath: wavPath);

/// Preview a voice — generates TTS, saves preview WAV, plays it. Returns preview path.
Future<String> previewVoice({required String voicePath}) =>
    RustLib.instance.api.crateApiEnginePreviewVoice(voicePath: voicePath);

/// Play a cached preview WAV (instant, no TTS). Blocking.
Future<bool> playPreview({required String previewWavPath}) => RustLib
    .instance
    .api
    .crateApiEnginePlayPreview(previewWavPath: previewWavPath);

/// Delete a voice and its files.
Future<bool> deleteVoice({required String voicePath}) =>
    RustLib.instance.api.crateApiEngineDeleteVoice(voicePath: voicePath);

/// Get the project voices directory path.
String voicesDir() => RustLib.instance.api.crateApiEngineVoicesDir();

Future<List<FfiVoiceInfo>> listBuiltinVoices() =>
    RustLib.instance.api.crateApiEngineListBuiltinVoices();

class FfiAudioDevice {
  final String name;
  final bool isDefault;
  final bool isInput;

  const FfiAudioDevice({
    required this.name,
    required this.isDefault,
    required this.isInput,
  });

  @override
  int get hashCode => name.hashCode ^ isDefault.hashCode ^ isInput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAudioDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDefault == other.isDefault &&
          isInput == other.isInput;
}

class FfiEngineConfig {
  final String sttBackend;
  final String sttLanguage;
  final String translateFrom;
  final String translateTo;
  final String voicePath;
  final double ttsSpeed;
  final String groqApiKey;
  final String deepgramApiKey;
  final String hfToken;
  final String parakeetModelDir;
  final String vadModelPath;
  final String audioOutput;

  const FfiEngineConfig({
    required this.sttBackend,
    required this.sttLanguage,
    required this.translateFrom,
    required this.translateTo,
    required this.voicePath,
    required this.ttsSpeed,
    required this.groqApiKey,
    required this.deepgramApiKey,
    required this.hfToken,
    required this.parakeetModelDir,
    required this.vadModelPath,
    required this.audioOutput,
  });

  @override
  int get hashCode =>
      sttBackend.hashCode ^
      sttLanguage.hashCode ^
      translateFrom.hashCode ^
      translateTo.hashCode ^
      voicePath.hashCode ^
      ttsSpeed.hashCode ^
      groqApiKey.hashCode ^
      deepgramApiKey.hashCode ^
      hfToken.hashCode ^
      parakeetModelDir.hashCode ^
      vadModelPath.hashCode ^
      audioOutput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiEngineConfig &&
          runtimeType == other.runtimeType &&
          sttBackend == other.sttBackend &&
          sttLanguage == other.sttLanguage &&
          translateFrom == other.translateFrom &&
          translateTo == other.translateTo &&
          voicePath == other.voicePath &&
          ttsSpeed == other.ttsSpeed &&
          groqApiKey == other.groqApiKey &&
          deepgramApiKey == other.deepgramApiKey &&
          hfToken == other.hfToken &&
          parakeetModelDir == other.parakeetModelDir &&
          vadModelPath == other.vadModelPath &&
          audioOutput == other.audioOutput;
}

@freezed
sealed class FfiEngineEvent with _$FfiEngineEvent {
  const FfiEngineEvent._();

  const factory FfiEngineEvent.statusChanged({required String status}) =
      FfiEngineEvent_StatusChanged;
  const factory FfiEngineEvent.transcript({
    required String original,
    required String translated,
  }) = FfiEngineEvent_Transcript;
  const factory FfiEngineEvent.error({required String message}) =
      FfiEngineEvent_Error;
  const factory FfiEngineEvent.log({
    required String level,
    required String message,
  }) = FfiEngineEvent_Log;
}

class FfiModelStatus {
  final bool sttReady;
  final String sttPath;
  final bool vadReady;
  final String vadPath;
  final bool voiceReady;
  final String voicePath;

  const FfiModelStatus({
    required this.sttReady,
    required this.sttPath,
    required this.vadReady,
    required this.vadPath,
    required this.voiceReady,
    required this.voicePath,
  });

  @override
  int get hashCode =>
      sttReady.hashCode ^
      sttPath.hashCode ^
      vadReady.hashCode ^
      vadPath.hashCode ^
      voiceReady.hashCode ^
      voicePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiModelStatus &&
          runtimeType == other.runtimeType &&
          sttReady == other.sttReady &&
          sttPath == other.sttPath &&
          vadReady == other.vadReady &&
          vadPath == other.vadPath &&
          voiceReady == other.voiceReady &&
          voicePath == other.voicePath;
}

class FfiVoiceInfo {
  final String name;
  final String path;
  final bool isPrecomputed;
  final BigInt sizeBytes;

  const FfiVoiceInfo({
    required this.name,
    required this.path,
    required this.isPrecomputed,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isPrecomputed.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiVoiceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isPrecomputed == other.isPrecomputed &&
          sizeBytes == other.sizeBytes;
}
