// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Ping — verifies FFI bridge works.
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Returns the engine version.
String engineVersion() => RustLib.instance.api.crateApiSimpleEngineVersion();

/// Test async function — simulates a slow operation.
Future<String> testAsync({required int delayMs}) =>
    RustLib.instance.api.crateApiSimpleTestAsync(delayMs: delayMs);

/// Test streaming — sends events to Dart at intervals.
Stream<String> testStream({required int count, required int intervalMs}) =>
    RustLib.instance.api.crateApiSimpleTestStream(
      count: count,
      intervalMs: intervalMs,
    );
